package com.example.jeremy.artgenerator.constants;

public enum AnimationType {
    ANIMATE_DEFAULT_USER_DATA,
    ANIMATE_LOST_INTERNET_CONNECTION,
    ANIMATE_INVALID_SIGN_UP_DATA,
    ANIMATE_INVALID_SIGN_IN_DATA,
    ANIMATE_EMPTY_FIELDS,
    ANIMATE_SERVER_NOT_RESPONDING,
    ANIMATE_INVALID_RESTORE_DATA,
    ANIMATE_RESTORED_DATA
}
